name: Docker

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Build latest docker release
    runs-on: ubuntu-latest
    env:
      GITHUB_URL: https://github.com/${{ github.repository }}
      IMAGE: ulixee/ulixee-cloud

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        shell: bash
        working-directory: cloud/main
        run: export VERSION=$(node -p "require('./package.json').version") && echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install yarn packages
        run: yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Chrome Versions
        shell: bash
        run: |
          CHROME_PACKAGE=$(yarn list --pattern '@ulixee/chrome-' --depth=0 | grep '@ulixee/chrome-' | grep -Eo 'chrome-[0-9]+-0' | head -1)

          CHROME_VERSION=$(echo $CHROME_PACKAGE | awk -F'-' '{print $2}')
          PREVIOUS_CHROME_VERSION=$((CHROME_VERSION - 1))

          echo "ADD_CHROME_VERSION=$PREVIOUS_CHROME_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        shell: bash
        working-directory: cloud/tools/docker
        run: |
          export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Building Docker image: ${VERSION}"

          docker build \
            --progress auto \
            --cache-from ghcr.io/${IMAGE}:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg ADD_TO_INSTALL="yarn add "@ulixee/chrome-$ADD_CHROME_VERSION-0"" \
            --build-arg VERSION=${VERSION} \
            \
            --tag ghcr.io/${IMAGE}:v${VERSION} \
            --tag ghcr.io/${IMAGE}:latest \
            --tag docker.io/${IMAGE}:v${VERSION} \
            --tag docker.io/${IMAGE}:latest \
            \
            --label org.label-schema.build-date=${BUILD_DATE} \
            --label org.label-schema.vcs-url=${GITHUB_URL} \
            --label org.label-schema.vcs-ref=${GITHUB_SHA} \
            \
            --label org.opencontainers.image.created=${BUILD_DATE} \
            --label org.opencontainers.image.source=${GITHUB_URL} \
            --label org.opencontainers.image.revision=${GITHUB_SHA} \
            .

      - name: Push Image to GHCR
        run: docker push -a ghcr.io/${IMAGE}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Dockerhub
        run: docker push -a docker.io/${IMAGE}
