name: Deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install Packages and Build Website
        run: |
          cd website
          yarn install
          yarn build
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: website/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
